app:
  port: 8080
  host: 0.0.0.0
  env: dev
  logfiles: /logs

log:
  level: 0
  format: plain
  director: /logs
  show-line: true

redis:
  enable: true
  host: 117.50.46.248
  port: 6379
  password:
  db: 0

database:
  driver: mysql
  migrate: true
  # use dsn
  dsn: root:123456@tcp(117.50.46.248:3306)/Interesting-Talks?charset=utf8mb4&parseTime=True&loc=Local&timeout=1000ms
